## Step 1 - Check dataset quality and class imbalance
### Dataset 1

In [1]:

import pandas as pd
from google.colab import files

uploaded = files.upload()

for filename in uploaded.keys():
    print("\n" + "=" * 60)
    print("DATASET:", filename)
    print("=" * 60)

    df = pd.read_csv(filename)

    print("\n1. Dataset shape:", df.shape)

    print("\n2. First 5 rows:")
    display(df.head())

    print("\n3. Column names:")
    print(df.columns.tolist())

    print("\n4. Duplicate rows:", df.duplicated().sum())

    print("\n5. Missing values:")
    missing = df.isnull().sum()
    print("Total missing cells:", missing.sum())
    print(missing[missing > 0].sort_values(ascending=False))

    print("\n6. Duplicate column names:",
          df.columns[df.columns.duplicated()].tolist())

    print("\n7. Data types:")
    print(df.dtypes.value_counts())

    print("\n8. Possible label columns:")
    for col in df.columns:
        if any(word in col.lower()
               for word in ["label", "class", "target", "result"]):
            print(f"\nColumn: {col}")
            print(df[col].value_counts(dropna=False))

Saving Phishing_Legitimate_full.csv to Phishing_Legitimate_full.csv

============================================================
DATASET: Phishing_Legitimate_full.csv
============================================================

1. Dataset shape: (10000, 50)

2. First 5 rows:

,id,NumDots,SubdomainLevel,PathLevel,UrlLength,NumDash,NumDashInHostname,AtSymbol,TildeSymbol,NumUnderscore,...,IframeOrFrame,MissingTitle,ImagesOnlyInForm,SubdomainLevelRT,UrlLengthRT,PctExtResourceUrlsRT,AbnormalExtFormActionR,ExtMetaScriptLinkRT,PctExtNullSelfRedirectHyperlinksRT,CLASS_LABEL
0,1,3,1,5,72,0,0,0,0,0,...,0,0,1,1,0,1,1,-1,1,1
1,2,3,1,3,144,0,0,0,0,2,...,0,0,0,1,-1,1,1,1,1,1
2,3,3,1,2,58,0,0,0,0,0,...,0,0,0,1,0,-1,1,-1,0,1
3,4,3,1,6,79,1,0,0,0,0,...,0,0,0,1,-1,1,1,1,-1,1
4,5,3,0,4,46,0,0,0,0,0,...,1,0,0,1,1,-1,0,-1,-1,1

3. Column names:
['id', 'NumDots', 'SubdomainLevel', 'PathLevel', 'UrlLength', 'NumDash', 'NumDashInHostname', 'AtSymbol', 'TildeSymbol', 'NumUnderscore', 'NumPercent', 'NumQueryComponents', 'NumAmpersand', 'NumHash', 'NumNumericChars', 'NoHttps', 'RandomString', 'IpAddress', 'DomainInSubdomains', 'DomainInPaths', 'HttpsInHostname', 'HostnameLength', 'PathLength', 'QueryLength', 'DoubleSlashInPath', 'NumSensitiveWords', 'EmbeddedBrandName', 'PctExtHyperlinks', 'PctExtResourceUrls', 'ExtFavicon', 'InsecureForms', 'RelativeFormAction', 'ExtFormAction', 'AbnormalFormAction', 'PctNullSelfRedirectHyperlinks', 'FrequentDomainNameMismatch', 'FakeLinkInStatusBar', 'RightClickDisabled', 'PopUpWindow', 'SubmitInfoToEmail', 'IframeOrFrame', 'MissingTitle', 'ImagesOnlyInForm', 'SubdomainLevelRT', 'UrlLengthRT', 'PctExtResourceUrlsRT', 'AbnormalExtFormActionR', 'ExtMetaScriptLinkRT', 'PctExtNullSelfRedirectHyperlinksRT', 'CLASS_LABEL']

4. Duplicate rows: 0

5. Missing values:
Total missing cells: 0
Series([], dtype: int64)

6. Duplicate column names: []

7. Data types:
int64      47
float64     3
Name: count, dtype: int64

8. Possible label columns:

Column: CLASS_LABEL
CLASS_LABEL
1    5000
0    5000
Name: count, dtype: int64

Conclusion: No missing values, duplicate rows or duplicate column names were detected. The classes have an exact 50:50 distribution, so there is no class imbalance in this dataset.


### Dataset 2

In [2]:

import pandas as pd
from google.colab import files

uploaded = files.upload()

for filename in uploaded.keys():
    print("\n" + "=" * 60)
    print("DATASET:", filename)
    print("=" * 60)

    df = pd.read_csv(filename)

    print("\n1. Dataset shape:", df.shape)

    print("\n2. First 5 rows:")
    display(df.head())

    print("\n3. Column names:")
    print(df.columns.tolist())

    print("\n4. Duplicate rows:", df.duplicated().sum())

    print("\n5. Missing values:")
    missing = df.isnull().sum()
    print("Total missing cells:", missing.sum())
    print(missing[missing > 0].sort_values(ascending=False))

    print("\n6. Duplicate column names:",
          df.columns[df.columns.duplicated()].tolist())

    print("\n7. Data types:")
    print(df.dtypes.value_counts())

    print("\n8. Possible label columns:")
    for col in df.columns:
        if any(word in col.lower()
               for word in ["label", "class", "target", "result"]):
            print(f"\nColumn: {col}")
            print(df[col].value_counts(dropna=False))

Saving dataset_full.csv to dataset_full.csv

============================================================
DATASET: dataset_full.csv
============================================================

1. Dataset shape: (88647, 112)

2. First 5 rows:

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,3,0,0,1,0,0,0,0,0,0,...,1,2,0,892,0,0,0,0,0,1
1,5,0,1,3,0,3,0,2,0,0,...,1,2,1,9540,1,0,0,0,0,1
2,2,0,0,1,0,0,0,0,0,0,...,1,2,3,589,1,0,0,0,0,0
3,4,0,2,5,0,0,0,0,0,0,...,1,2,0,292,1,0,0,0,0,1
4,2,0,0,0,0,0,0,0,0,0,...,1,2,1,3597,0,1,0,0,0,0

3. Column names:
['qty_dot_url', 'qty_hyphen_url', 'qty_underline_url', 'qty_slash_url', 'qty_questionmark_url', 'qty_equal_url', 'qty_at_url', 'qty_and_url', 'qty_exclamation_url', 'qty_space_url', 'qty_tilde_url', 'qty_comma_url', 'qty_plus_url', 'qty_asterisk_url', 'qty_hashtag_url', 'qty_dollar_url', 'qty_percent_url', 'qty_tld_url', 'length_url', 'qty_dot_domain', 'qty_hyphen_domain', 'qty_underline_domain', 'qty_slash_domain', 'qty_questionmark_domain', 'qty_equal_domain', 'qty_at_domain', 'qty_and_domain', 'qty_exclamation_domain', 'qty_space_domain', 'qty_tilde_domain', 'qty_comma_domain', 'qty_plus_domain', 'qty_asterisk_domain', 'qty_hashtag_domain', 'qty_dollar_domain', 'qty_percent_domain', 'qty_vowels_domain', 'domain_length', 'domain_in_ip', 'server_client_domain', 'qty_dot_directory', 'qty_hyphen_directory', 'qty_underline_directory', 'qty_slash_directory', 'qty_questionmark_directory', 'qty_equal_directory', 'qty_at_directory', 'qty_and_directory', 'qty_exclamation_directory', 'qty_space_directory', 'qty_tilde_directory', 'qty_comma_directory', 'qty_plus_directory', 'qty_asterisk_directory', 'qty_hashtag_directory', 'qty_dollar_directory', 'qty_percent_directory', 'directory_length', 'qty_dot_file', 'qty_hyphen_file', 'qty_underline_file', 'qty_slash_file', 'qty_questionmark_file', 'qty_equal_file', 'qty_at_file', 'qty_and_file', 'qty_exclamation_file', 'qty_space_file', 'qty_tilde_file', 'qty_comma_file', 'qty_plus_file', 'qty_asterisk_file', 'qty_hashtag_file', 'qty_dollar_file', 'qty_percent_file', 'file_length', 'qty_dot_params', 'qty_hyphen_params', 'qty_underline_params', 'qty_slash_params', 'qty_questionmark_params', 'qty_equal_params', 'qty_at_params', 'qty_and_params', 'qty_exclamation_params', 'qty_space_params', 'qty_tilde_params', 'qty_comma_params', 'qty_plus_params', 'qty_asterisk_params', 'qty_hashtag_params', 'qty_dollar_params', 'qty_percent_params', 'params_length', 'tld_present_params', 'qty_params', 'email_in_url', 'time_response', 'domain_spf', 'asn_ip', 'time_domain_activation', 'time_domain_expiration', 'qty_ip_resolved', 'qty_nameservers', 'qty_mx_servers', 'ttl_hostname', 'tls_ssl_certificate', 'qty_redirects', 'url_google_index', 'domain_google_index', 'url_shortened', 'phishing']

4. Duplicate rows: 1438

5. Missing values:
Total missing cells: 0
Series([], dtype: int64)

6. Duplicate column names: []

7. Data types:
int64      111
float64      1
Name: count, dtype: int64

8. Possible label columns:

##Step 2 — Check class balance and duplicate rows
### Dataset 2

In [3]:

import pandas as pd

df111 = pd.read_csv("dataset_full.csv")

# 1. Check target distribution
print("CLASS DISTRIBUTION")
counts = df111["phishing"].value_counts(dropna=False).sort_index()
print(counts)

print("\nCLASS PERCENTAGES")
print((df111["phishing"].value_counts(normalize=True, dropna=False)
       * 100).sort_index().round(2))

# 2. Check whether target values are valid
print("\nTARGET VALUES:", sorted(df111["phishing"].dropna().unique()))
print("Missing target labels:", df111["phishing"].isna().sum())

# 3. Investigate exact duplicate rows
duplicates = df111[df111.duplicated(keep=False)]
print("\nRows involved in exact duplicates:", len(duplicates))

print("\nLabels among duplicate rows:")
print(duplicates["phishing"].value_counts(dropna=False))

# 4. Check whether identical FEATURES have conflicting labels
feature_cols = [c for c in df111.columns if c != "phishing"]
label_counts = df111.groupby(feature_cols, dropna=False)["phishing"].nunique()
print("\nIdentical feature rows with conflicting labels:",
      (label_counts > 1).sum())

CLASS DISTRIBUTION
phishing
0    58000
1    30647
Name: count, dtype: int64

CLASS PERCENTAGES
phishing
0    65.43
1    34.57
Name: proportion, dtype: float64

TARGET VALUES: [np.int64(0), np.int64(1)]
Missing target labels: 0

Rows involved in exact duplicates: 1926

Labels among duplicate rows:
phishing
0    1715
1     211
Name: count, dtype: int64

Identical feature rows with conflicting labels: 6

What these results mean
- Class imbalance: The legitimate class is about 1.89 times as large as the phishing class. This is manageable; we don't automatically need oversampling. We'll use stratified splitting and evaluate precision, recall, F1 and ROC-AUC alongside accuracy.
- Duplicates: Your two duplicate counts are different because 1,438 counts repeated occurrences beyond the first, while 1,926 counts all rows belonging to duplicate groups.
- Conflicting labels: Six feature combinations have more than one target label. The same feature values mapping to different labels is worth investigating. We shouldn't arbitrarily remove records or relabel them.

### Investigate duplicates before cleaning

In [4]:

import pandas as pd

df111 = pd.read_csv("dataset_full.csv")

feature_cols = [c for c in df111.columns if c != "phishing"]

# Find feature combinations associated with multiple labels
label_counts = (
    df111.groupby(feature_cols, dropna=False)["phishing"]
    .agg(["count", "nunique"])
    .reset_index()
)

conflicts = label_counts[label_counts["nunique"] > 1]

print("Conflicting feature combinations:", len(conflicts))
print("\nConflicting combinations and their feature values:")
display(conflicts)

# Show the original records for those combinations
if len(conflicts) > 0:
    conflicting_rows = df111.merge(
        conflicts[feature_cols],
        on=feature_cols,
        how="inner"
    )
    print("\nOriginal rows with conflicting labels:")
    display(conflicting_rows.sort_values(feature_cols).head(30))

# Inspect repeated records and label agreement
print("\nExact duplicate rows beyond first occurrence:",
      df111.duplicated().sum())

print("\nClass counts before any cleaning:")
print(df111["phishing"].value_counts())

Conflicting feature combinations: 6

Conflicting combinations and their feature values:

/tmp/ipykernel_1072/1856874426.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/tmp/ipykernel_1072/1856874426.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/tmp/ipykernel_1072/1856874426.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/tmp/ipykernel_1072/1856874426.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/tmp/ipykernel_1072/1856874426.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/tmp/ipykernel_1072/1856874426.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/tmp/ipykernel_1072/1856874426.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/tmp/ipykernel_1072/1856874426.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/tmp/ipykernel_1072/1856874426.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/tmp/ipykernel_1072/1856874426.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/tmp/ipykernel_1072/1856874426.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/tmp/ipykernel_1072/1856874426.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,count,nunique
810,1,0,0,0,0,0,0,0,0,0,...,4,0,-1,0,-1,0,0,0,3,2
7441,1,0,0,1,0,0,0,0,0,0,...,4,0,-1,0,-1,0,0,0,2,2
43033,2,0,0,0,0,0,0,0,0,0,...,4,0,-1,0,-1,0,0,0,2,2
49427,2,0,0,1,0,0,0,0,0,0,...,4,0,-1,0,-1,0,0,0,2,2
50684,2,0,0,1,0,0,0,0,0,0,...,0,0,-1,0,-1,0,0,0,2,2
63282,2,1,0,1,0,0,0,0,0,0,...,4,0,-1,0,-1,0,0,0,2,2

Original rows with conflicting labels:

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,1,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,1
5,1,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
12,1,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
6,1,0,0,1,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,1
11,1,0,0,1,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
7,2,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
9,2,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,1
2,2,0,0,1,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
4,2,0,0,1,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,1
3,2,0,0,1,0,0,0,0,0,0,...,-1,0,0,-1,0,-1,0,0,0,0
10,2,0,0,1,0,0,0,0,0,0,...,-1,0,0,-1,0,-1,0,0,0,1
1,2,1,0,1,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,1
8,2,1,0,1,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0

Exact duplicate rows beyond first occurrence: 1438

Class counts before any cleaning:
phishing
0    58000
1    30647
Name: count, dtype: int64

What we learned
- 88,647 records and 111 features.
- No missing values and no duplicate column names.
- 65.43% legitimate, 34.57% phishing — moderately imbalanced, but we can start with stratified splitting and suitable metrics.
- 1,438 exact duplicate rows beyond their first occurrences.
- 6 identical feature combinations with conflicting labels.

The conflicting records have feature values such as ttl_hostname = -1, qty_redirects = -1, and qty_ip_resolved = -1. These may represent unavailable or unknown information, depending on the dataset's encoding. We shouldn't treat -1 as missing automatically without confirming that convention.

### Cleaning

In [5]:

import pandas as pd

df111 = pd.read_csv("dataset_full.csv")

target = "phishing"
features = [c for c in df111.columns if c != target]

# Step 1: Identify feature combinations with conflicting labels
label_counts = (
    df111.groupby(features, dropna=False)[target]
    .nunique()
)

conflicting_features = label_counts[label_counts > 1].index

print("Conflicting feature combinations:", len(conflicting_features))

# Step 2: Flag all records belonging to conflicting combinations
feature_index = pd.MultiIndex.from_frame(df111[features])
conflict_index = pd.MultiIndex.from_tuples(
    list(conflicting_features),
    names=features
)
conflict_mask = feature_index.isin(conflict_index)

print("Records excluded due to conflicting labels:",
      int(conflict_mask.sum()))

# Step 3: Exclude those ambiguous combinations
df_clean = df111.loc[~conflict_mask].copy()

# Step 4: Remove exact duplicate rows
before_dedup = len(df_clean)
df_clean = df_clean.drop_duplicates().reset_index(drop=True)

print("\nRows before cleaning:", len(df111))
print("Rows after conflict removal and deduplication:", len(df_clean))
print("Rows removed:", len(df111) - len(df_clean))

print("\nCleaned class distribution:")
print(df_clean[target].value_counts())

print("\nCleaned class percentages:")
print((df_clean[target].value_counts(normalize=True) * 100).round(2))

print("\nMissing values:", df_clean.isnull().sum().sum())
print("Remaining exact duplicates:", df_clean.duplicated().sum())

Conflicting feature combinations: 6
Records excluded due to conflicting labels: 13

Rows before cleaning: 88647
Rows after conflict removal and deduplication: 87197
Rows removed: 1450

Cleaned class distribution:
phishing
0    56706
1    30491
Name: count, dtype: int64

Cleaned class percentages:
phishing
0    65.03
1    34.97
Name: proportion, dtype: float64

Missing values: 0
Remaining exact duplicates: 0

Final cleaning results

The cleaned class distribution is:
- Legitimate (0): 56,706 — 65.03%
- Phishing (1): 30,491 — 34.97%
The dataset remains moderately imbalanced. That's okay—we'll preserve the class proportions during splitting and assess more than accuracy.

## Step 3 — Train-Test Split
(for the 111-feature dataset)

In [6]:

from sklearn.model_selection import train_test_split

def load_and_prepare_data_111(df_clean):

    # Separate features and target
    X = df_clean.drop(columns=["phishing"])
    y = df_clean["phishing"]

    # Train-test split: same 70:30 ratio
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        train_size=0.70,
        test_size=0.30,
        stratify=y,
        random_state=42
    )

    return X_train, X_test, y_train, y_test


X_train, X_test, y_train, y_test = load_and_prepare_data_111(df_clean)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

print("\nTraining class distribution:")
print(y_train.value_counts())

print("\nTesting class distribution:")
print(y_test.value_counts())

X_train shape: (61037, 111)
X_test shape: (26160, 111)
y_train shape: (61037,)
y_test shape: (26160,)

Training class distribution:
phishing
0    39694
1    21343
Name: count, dtype: int64

Testing class distribution:
phishing
0    17012
1     9148
Name: count, dtype: int64

The class distribution is also preserved closely across both sets.
- Training: 39,694 legitimate (class 0), 21,343 phishing (class 1).
- Testing: 17,012 legitimate (class 0), 9,148 phishing (class 1).

This confirms that stratify=y has maintained approximately the same class proportions in both sets. Your random_state=42 also makes the split reproducible.

##Step 4 - Train baseline ML models

(111 Features dataset)

In [7]:

# STEP 4: Train Baseline ML Models (111 Features)

import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)
from xgboost import XGBClassifier

models = {
    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(max_iter=2000, random_state=42))
    ]),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(
        n_estimators=100, random_state=42, n_jobs=-1
    ),
    "XGBoost": XGBClassifier(
        n_estimators=100,
        random_state=42,
        eval_metric="logloss",
        n_jobs=-1
    )
}

results = []

for name, model in models.items():
    print(f"Training {name}...")
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred, zero_division=0),
        "Recall": recall_score(y_test, y_pred, zero_division=0),
        "F1-Score": f1_score(y_test, y_pred, zero_division=0),
        "ROC-AUC": roc_auc_score(y_test, y_prob)
    })

results_df = pd.DataFrame(results)
print("\nBaseline Model Results:")
display(results_df.round(4))

Training Logistic Regression...
Training Decision Tree...
Training Random Forest...
Training XGBoost...

Baseline Model Results:

                 Model  Accuracy  Precision  Recall  F1-Score  ROC-AUC
0  Logistic Regression    0.9336     0.8970  0.9153    0.9061   0.9792
1        Decision Tree    0.9522     0.9339  0.9291    0.9314   0.9468
2        Random Forest    0.9699     0.9556  0.9584    0.9570   0.9943
3              XGBoost    0.9693     0.9573  0.9550    0.9561   0.9947

On the 48-feature dataset, XGBoost leads on accuracy and F1-score, while Random Forest leads on those two metrics on the 111-feature dataset.

##Step 5 -  SHAP-based feature reduction
### Step 5A — SHAP analysis for the 48-feature dataset

In [8]:

# STEP 5A: SHAP-Based Feature Selection (48 Features)

import pandas as pd
import numpy as np
import shap
from xgboost import XGBClassifier

# 1. Train XGBoost using training data only
xgb_48 = XGBClassifier(
    n_estimators=100,
    random_state=42,
    eval_metric="logloss",
    n_jobs=-1
)

xgb_48.fit(X_train, y_train)

# 2. Calculate SHAP values on training data
explainer_48 = shap.TreeExplainer(xgb_48)
shap_values_48 = explainer_48.shap_values(X_train)

# Handle binary-classification SHAP output
if isinstance(shap_values_48, list):
    shap_matrix_48 = shap_values_48[1]
elif isinstance(shap_values_48, np.ndarray) and shap_values_48.ndim == 3:
    shap_matrix_48 = shap_values_48[:, :, 1]
else:
    shap_matrix_48 = shap_values_48

# 3. Calculate mean absolute SHAP importance
importance_48 = pd.DataFrame({
    "Feature": X_train.columns,
    "Mean_Abs_SHAP": np.abs(shap_matrix_48).mean(axis=0)
}).sort_values("Mean_Abs_SHAP", ascending=False)

# 4. Select the top 25 features
top_25_features = importance_48.head(25)["Feature"].tolist()

print("Top 25 features selected:")
display(importance_48.head(25).reset_index(drop=True))

print("\nNumber of selected features:", len(top_25_features))

Top 25 features selected:

                   Feature  Mean_Abs_SHAP
0            qty_slash_url       2.241943
1   time_domain_activation       1.468935
2         directory_length       0.904311
3               length_url       0.754845
4           qty_dot_domain       0.435511
5             ttl_hostname       0.336650
6                   asn_ip       0.313164
7      qty_slash_directory       0.239655
8            time_response       0.225057
9   time_domain_expiration       0.179900
10           qty_redirects       0.166493
11          qty_mx_servers       0.160529
12           domain_length       0.139173
13             file_length       0.126053
14              domain_spf       0.125593
15    qty_hyphen_directory       0.119614
16         qty_nameservers       0.115702
17       qty_vowels_domain       0.115585
18     tls_ssl_certificate       0.108389
19             qty_dot_url       0.098629
20         qty_ip_resolved       0.094560
21          qty_dot_params       0.094128
22             qty_tld_url       0.068649
23              qty_at_url       0.045897
24       qty_hyphen_domain       0.044645

Number of selected features: 25

Step 5A — Conclusion
- XGBoost was trained using the training partition, and SHAP values were used to rank the 48 features.
- The top 25 features were selected based on their mean absolute SHAP values.
- qty_slash_url was the most influential feature, with a mean absolute SHAP value of 2.241943, followed by time_domain_activation and directory_length.
- The reduced dataset will contain 25 features instead of 48, a reduction of approximately 47.9%.

### Step 5B — Select top 50 features from the 111-feature dataset

In [9]:

# STEP 5B: Select Top 50 Features from the 111-Feature Dataset

# Select the 50 highest-ranked features from the existing SHAP ranking
top_50_features_111 = importance_48.head(50)["Feature"].tolist()

print("Top 50 features selected for the 111-feature dataset:")
display(importance_48.head(50).reset_index(drop=True))

print("\nNumber of selected features:", len(top_50_features_111))

Top 50 features selected for the 111-feature dataset:

                      Feature  Mean_Abs_SHAP
0               qty_slash_url       2.241943
1      time_domain_activation       1.468935
2            directory_length       0.904311
3                  length_url       0.754845
4              qty_dot_domain       0.435511
5                ttl_hostname       0.336650
6                      asn_ip       0.313164
7         qty_slash_directory       0.239655
8               time_response       0.225057
9      time_domain_expiration       0.179900
10              qty_redirects       0.166493
11             qty_mx_servers       0.160529
12              domain_length       0.139173
13                file_length       0.126053
14                 domain_spf       0.125593
15       qty_hyphen_directory       0.119614
16            qty_nameservers       0.115702
17          qty_vowels_domain       0.115585
18        tls_ssl_certificate       0.108389
19                qty_dot_url       0.098629
20            qty_ip_resolved       0.094560
21             qty_dot_params       0.094128
22                qty_tld_url       0.068649
23                 qty_at_url       0.045897
24          qty_hyphen_domain       0.044645
25             qty_hyphen_url       0.041968
26              params_length       0.037078
27                 qty_params       0.036169
28              url_shortened       0.023971
29          qty_dot_directory       0.023287
30            qty_hyphen_file       0.021076
31               qty_dot_file       0.020208
32        qty_equal_directory       0.014342
33    qty_underline_directory       0.007974
34          qty_underline_url       0.007786
35            qty_percent_url       0.005505
36         qty_underline_file       0.005438
37           qty_percent_file       0.004762
38              qty_equal_url       0.004726
39               domain_in_ip       0.003926
40      qty_percent_directory       0.003283
41           qty_equal_params       0.002948
42               qty_plus_url       0.002230
43  qty_exclamation_directory       0.002051
44           qty_slash_params       0.001792
45         qty_percent_params       0.001056
46       qty_underline_params       0.001027
47             qty_comma_file       0.000890
48         tld_present_params       0.000663
49        qty_tilde_directory       0.000314

Number of selected features: 50

Conclusion:

  * SHAP analysis was used to rank the 111 features based on their mean absolute SHAP values.

  * The top 50 features were selected for the reduced dataset.

  * qty_slash_url was the most influential feature, followed by time_domain_activation, directory_length, length_url, and qty_dot_domain.

  * Feature dimensionality was reduced from 111 to 50, a 55.0% reduction.

  * The selected features will be used to train and evaluate all four machine learning models in Step 6.

The effect of feature reduction on predictive performance will be determined by comparing the reduced models against the original 111-feature baseline.

## Step 6 — Run all four models on feature reduced dataset
### Step 6A — Run all four models on the reduced 48-feature dataset

In [13]:

# STEP 6A - Setup: Load and split the original 48-feature dataset

import pandas as pd
from sklearn.model_selection import train_test_split

df48 = pd.read_csv("/content/Phishing_Legitimate_full.csv")

X48 = df48.drop(columns=["id", "CLASS_LABEL"])
y48 = df48["CLASS_LABEL"]

X_train_48, X_test_48, y_train_48, y_test_48 = train_test_split(
    X48,
    y48,
    train_size=0.70,
    test_size=0.30,
    stratify=y48,
    random_state=42
)

print("Training features:", X_train_48.shape)
print("Testing features:", X_test_48.shape)

Training features: (7000, 48)
Testing features: (3000, 48)

In [15]:

# Calculate SHAP importance for the original 48-feature dataset

import numpy as np
import shap
from xgboost import XGBClassifier

xgb_48 = XGBClassifier(
    n_estimators=100,
    random_state=42,
    eval_metric="logloss",
    n_jobs=-1
)

xgb_48.fit(X_train_48, y_train_48)

explainer_48 = shap.TreeExplainer(xgb_48)
shap_values_48 = explainer_48.shap_values(X_train_48)

if isinstance(shap_values_48, list):
    shap_matrix_48 = shap_values_48[1]
elif isinstance(shap_values_48, np.ndarray) and shap_values_48.ndim == 3:
    shap_matrix_48 = shap_values_48[:, :, 1]
else:
    shap_matrix_48 = shap_values_48

importance_48 = pd.DataFrame({
    "Feature": X_train_48.columns,
    "Mean_Abs_SHAP": np.abs(shap_matrix_48).mean(axis=0)
}).sort_values("Mean_Abs_SHAP", ascending=False)

top_25_features_48 = importance_48.head(25)["Feature"].tolist()

display(importance_48.head(25).reset_index(drop=True))
print("Selected features:", len(top_25_features_48))

                               Feature  Mean_Abs_SHAP
0                     PctExtHyperlinks       1.768827
1   PctExtNullSelfRedirectHyperlinksRT       1.512488
2        PctNullSelfRedirectHyperlinks       0.976562
3                   PctExtResourceUrls       0.934281
4                        InsecureForms       0.785042
5                              NumDash       0.772121
6                            PathLevel       0.720371
7           FrequentDomainNameMismatch       0.717133
8                      NumNumericChars       0.700066
9                              NumDots       0.587937
10                      SubdomainLevel       0.484436
11                          ExtFavicon       0.421075
12                   SubmitInfoToEmail       0.359874
13                   NumSensitiveWords       0.327230
14                           UrlLength       0.304487
15                       IframeOrFrame       0.288307
16                      HostnameLength       0.267068
17                       NumUnderscore       0.265377
18                          PathLength       0.236786
19                         QueryLength       0.235881
20                  RelativeFormAction       0.234717
21                   NumDashInHostname       0.223809
22                 ExtMetaScriptLinkRT       0.207014
23                  NumQueryComponents       0.181249
24                        RandomString       0.095435

Selected features: 25

In [16]:

# STEP 6A: Evaluate All Four Models on the Reduced 48-Feature Dataset

import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score
)
from xgboost import XGBClassifier

# 1. Keep only the selected top 25 features
X_train_25 = X_train_48[top_25_features_48]
X_test_25 = X_test_48[top_25_features_48]

print("Reduced training shape:", X_train_25.shape)
print("Reduced testing shape:", X_test_25.shape)

# 2. Define the four models
models_25 = {
    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(max_iter=2000, random_state=42))
    ]),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(
        n_estimators=100, random_state=42, n_jobs=-1
    ),
    "XGBoost": XGBClassifier(
        n_estimators=100,
        random_state=42,
        eval_metric="logloss",
        n_jobs=-1
    )
}

# 3. Train and evaluate each model
results_25 = []

for name, model in models_25.items():
    print(f"Training {name}...")
    model.fit(X_train_25, y_train_48)

    y_pred = model.predict(X_test_25)
    y_prob = model.predict_proba(X_test_25)[:, 1]

    results_25.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test_48, y_pred),
        "Precision": precision_score(y_test_48, y_pred, zero_division=0),
        "Recall": recall_score(y_test_48, y_pred, zero_division=0),
        "F1-Score": f1_score(y_test_48, y_pred, zero_division=0),
        "ROC-AUC": roc_auc_score(y_test_48, y_prob)
    })

results_25_df = pd.DataFrame(results_25)

print("\nResults: Reduced 48-Feature Dataset (Top 25 Features)")
display(results_25_df.round(4))

Reduced training shape: (7000, 25)
Reduced testing shape: (3000, 25)
Training Logistic Regression...
Training Decision Tree...
Training Random Forest...
Training XGBoost...

Results: Reduced 48-Feature Dataset (Top 25 Features)

                 Model  Accuracy  Precision  Recall  F1-Score  ROC-AUC
0  Logistic Regression    0.9433     0.9369  0.9507    0.9437   0.9831
1        Decision Tree    0.9643     0.9585  0.9707    0.9646   0.9643
2        Random Forest    0.9827     0.9820  0.9833    0.9827   0.9987
3              XGBoost    0.9860     0.9834  0.9887    0.9860   0.9985

Conclusion: Reduced 48-Feature Dataset

* SHAP was used to select the top 25 features from the original 48-feature dataset.

* All four machine learning models were trained and evaluated using the reduced feature set.

* XGBoost achieved the highest accuracy (98.60%), precision (98.34%), recall (98.87%) and F1-score (98.60%).

* Random Forest achieved the highest ROC-AUC of 99.87%, closely followed by XGBoost at 99.85%.

* The feature count was reduced by approximately 47.9% while maintaining strong predictive performance.

These results suggest that the selected 25 features retain substantial predictive information. The reduced models will be compared with their original-feature baselines to quantify the impact of feature reduction.

### Step 6B — Run all four models on the reduced 111-feature dataset

In [17]:

# STEP 6B: Evaluate Models on the Reduced 111-Feature Dataset

import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)
from xgboost import XGBClassifier

# 1. Select the top 50 SHAP-ranked features
X_train_50 = X_train[top_50_features_111]
X_test_50 = X_test[top_50_features_111]

print("Reduced training shape:", X_train_50.shape)
print("Reduced testing shape:", X_test_50.shape)

# 2. Define all four models
models_50 = {
    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(max_iter=2000, random_state=42))
    ]),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(
        n_estimators=100, random_state=42, n_jobs=-1
    ),
    "XGBoost": XGBClassifier(
        n_estimators=100,
        random_state=42,
        eval_metric="logloss",
        n_jobs=-1
    )
}

# 3. Train and evaluate each model
results_50 = []

for name, model in models_50.items():
    print(f"Training {name}...")
    model.fit(X_train_50, y_train)

    y_pred = model.predict(X_test_50)
    y_prob = model.predict_proba(X_test_50)[:, 1]

    results_50.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred, zero_division=0),
        "Recall": recall_score(y_test, y_pred, zero_division=0),
        "F1-Score": f1_score(y_test, y_pred, zero_division=0),
        "ROC-AUC": roc_auc_score(y_test, y_prob)
    })

results_50_df = pd.DataFrame(results_50)

print("\nResults: Reduced 111-Feature Dataset (Top 50 SHAP Features)")
display(results_50_df.round(4))

Reduced training shape: (61037, 50)
Reduced testing shape: (26160, 50)
Training Logistic Regression...
Training Decision Tree...
Training Random Forest...
Training XGBoost...

Results: Reduced 111-Feature Dataset (Top 50 SHAP Features)

                 Model  Accuracy  Precision  Recall  F1-Score  ROC-AUC
0  Logistic Regression    0.9338     0.8977  0.9150    0.9062   0.9792
1        Decision Tree    0.9540     0.9353  0.9329    0.9341   0.9491
2        Random Forest    0.9703     0.9565  0.9586    0.9575   0.9947
3              XGBoost    0.9703     0.9591  0.9558    0.9575   0.9948

**Conclusion: Reduced 111-Feature Dataset**

- SHAP analysis was used to select the top 50 features from the original 111-feature dataset.
- All four machine learning models were trained and evaluated using the reduced feature set.
- Random Forest and XGBoost achieved the highest accuracy of **97.03%** and the highest F1-score of **95.75%**.
- XGBoost achieved the highest ROC-AUC of **99.48%**, marginally higher than Random Forest at 99.47%.
- The feature count was reduced from 111 to 50, representing a **55.0% reduction**, while maintaining strong predictive performance.

These results indicate that the selected 50 features retain substantial predictive information. The reduced models will be compared against the original-feature baselines and the reduced 48-feature models to support final model selection.

## Step 7 — Feature Practicality

### 7.1. Reduced 48-feature dataset — Top 25 SHAP features

In [18]:

import pandas as pd

features_48 = [
    {
        "Feature": "PctExtHyperlinks",
        "Category": "Webpage content",
        "Extraction_Method": "Parse HTML and count external hyperlinks",
        "Practicality": "Medium",
        "Reason": "Requires access to webpage HTML"
    },
    {
        "Feature": "PctExtNullSelfRedirectHyperlinksRT",
        "Category": "Webpage content / links",
        "Extraction_Method": "Inspect hyperlinks and classify null, self and redirect behavior",
        "Practicality": "Low-Medium",
        "Reason": "Requires HTML analysis and potentially redirect behavior checks"
    },
    {
        "Feature": "PctNullSelfRedirectHyperlinks",
        "Category": "Webpage content / links",
        "Extraction_Method": "Inspect hyperlink destinations and relative or self references",
        "Practicality": "Medium",
        "Reason": "Requires parsing webpage links"
    },
    {
        "Feature": "PctExtResourceUrls",
        "Category": "Webpage resources",
        "Extraction_Method": "Parse HTML resource references and identify external resources",
        "Practicality": "Medium",
        "Reason": "Requires HTML and resource URL analysis"
    },
    {
        "Feature": "InsecureForms",
        "Category": "Webpage forms",
        "Extraction_Method": "Inspect form actions and security-related properties",
        "Practicality": "Medium",
        "Reason": "Requires HTML form analysis"
    },
    {
        "Feature": "NumDash",
        "Category": "URL string",
        "Extraction_Method": "Count hyphens in the URL",
        "Practicality": "High",
        "Reason": "Can be computed directly from the URL string"
    },
    {
        "Feature": "PathLevel",
        "Category": "URL structure",
        "Extraction_Method": "Parse URL path and count directory levels",
        "Practicality": "High",
        "Reason": "Usually available from URL parsing"
    },
    {
        "Feature": "FrequentDomainNameMismatch",
        "Category": "Domain / webpage",
        "Extraction_Method": "Compare the domain with relevant page or link identity indicators",
        "Practicality": "Medium-Low",
        "Reason": "Exact calculation depends on the dataset's feature definition"
    },
    {
        "Feature": "NumNumericChars",
        "Category": "URL string",
        "Extraction_Method": "Count numeric characters in the URL",
        "Practicality": "High",
        "Reason": "Can be computed directly from the URL string"
    },
    {
        "Feature": "NumDots",
        "Category": "URL string",
        "Extraction_Method": "Count dots in the URL",
        "Practicality": "High",
        "Reason": "Can be computed directly from the URL string"
    },
    {
        "Feature": "SubdomainLevel",
        "Category": "URL / domain",
        "Extraction_Method": "Parse hostname and determine subdomain depth",
        "Practicality": "High",
        "Reason": "Requires reliable hostname parsing"
    },
    {
        "Feature": "ExtFavicon",
        "Category": "Webpage resources",
        "Extraction_Method": "Inspect favicon reference and compare its origin",
        "Practicality": "Medium",
        "Reason": "Requires HTML inspection and possibly URL resolution"
    },
    {
        "Feature": "SubmitInfoToEmail",
        "Category": "Webpage forms",
        "Extraction_Method": "Inspect form actions for email-submission behavior",
        "Practicality": "Medium",
        "Reason": "Requires HTML form inspection"
    },
    {
        "Feature": "NumSensitiveWords",
        "Category": "URL / webpage text",
        "Extraction_Method": "Count sensitive terms in the exact text field defined by the dataset",
        "Practicality": "Medium",
        "Reason": "Must verify whether the source definition uses URL text or page content"
    },
    {
        "Feature": "UrlLength",
        "Category": "URL string",
        "Extraction_Method": "Measure URL string length",
        "Practicality": "High",
        "Reason": "Can be computed directly from the URL string"
    },
    {
        "Feature": "IframeOrFrame",
        "Category": "Webpage content",
        "Extraction_Method": "Inspect HTML for iframe or frame elements",
        "Practicality": "Medium",
        "Reason": "Requires access to webpage HTML"
    },
    {
        "Feature": "HostnameLength",
        "Category": "URL / domain",
        "Extraction_Method": "Parse URL and measure hostname length",
        "Practicality": "High",
        "Reason": "Can be computed from the hostname"
    },
    {
        "Feature": "NumUnderscore",
        "Category": "URL string",
        "Extraction_Method": "Count underscores in the URL",
        "Practicality": "High",
        "Reason": "Can be computed directly from the URL string"
    },
    {
        "Feature": "PathLength",
        "Category": "URL structure",
        "Extraction_Method": "Parse URL and measure path length",
        "Practicality": "High",
        "Reason": "Can be computed from the URL string"
    },
    {
        "Feature": "QueryLength",
        "Category": "URL structure",
        "Extraction_Method": "Parse query component and measure its length",
        "Practicality": "High",
        "Reason": "Can be computed from the URL string"
    },
    {
        "Feature": "RelativeFormAction",
        "Category": "Webpage forms",
        "Extraction_Method": "Inspect form action attributes and determine whether they are relative",
        "Practicality": "Medium",
        "Reason": "Requires HTML form analysis"
    },
    {
        "Feature": "NumDashInHostname",
        "Category": "URL / domain",
        "Extraction_Method": "Parse hostname and count hyphens",
        "Practicality": "High",
        "Reason": "Can be computed from the hostname"
    },
    {
        "Feature": "ExtMetaScriptLinkRT",
        "Category": "Webpage resources",
        "Extraction_Method": "Inspect metadata, scripts and links for external references",
        "Practicality": "Medium",
        "Reason": "Requires HTML parsing and the original feature definition"
    },
    {
        "Feature": "NumQueryComponents",
        "Category": "URL structure",
        "Extraction_Method": "Parse query string and count components",
        "Practicality": "High",
        "Reason": "Can be computed from the URL string"
    },
    {
        "Feature": "RandomString",
        "Category": "URL / webpage text",
        "Extraction_Method": "Apply the dataset's original random-string detection rule",
        "Practicality": "Medium",
        "Reason": "Requires the exact source definition and detection rule"
    }
]

df_48_practicality = pd.DataFrame(features_48)

display(df_48_practicality)

df_48_practicality.to_csv(
    "feature_practicality_48_reduced.csv",
    index=False
)

print("Saved: feature_practicality_48_reduced.csv")

,Feature,Category,Extraction_Method,Practicality,Reason
0,PctExtHyperlinks,Webpage content,Parse HTML and count external hyperlinks,Medium,Requires access to webpage HTML
1,PctExtNullSelfRedirectHyperlinksRT,Webpage content / links,"Inspect hyperlinks and classify null, self and...",Low-Medium,Requires HTML analysis and potentially redirec...
2,PctNullSelfRedirectHyperlinks,Webpage content / links,Inspect hyperlink destinations and relative or...,Medium,Requires parsing webpage links
3,PctExtResourceUrls,Webpage resources,Parse HTML resource references and identify ex...,Medium,Requires HTML and resource URL analysis
4,InsecureForms,Webpage forms,Inspect form actions and security-related prop...,Medium,Requires HTML form analysis
5,NumDash,URL string,Count hyphens in the URL,High,Can be computed directly from the URL string
6,PathLevel,URL structure,Parse URL path and count directory levels,High,Usually available from URL parsing
7,FrequentDomainNameMismatch,Domain / webpage,Compare the domain with relevant page or link ...,Medium-Low,Exact calculation depends on the dataset's fea...
8,NumNumericChars,URL string,Count numeric characters in the URL,High,Can be computed directly from the URL string
9,NumDots,URL string,Count dots in the URL,High,Can be computed directly from the URL string
10,SubdomainLevel,URL / domain,Parse hostname and determine subdomain depth,High,Requires reliable hostname parsing
11,ExtFavicon,Webpage resources,Inspect favicon reference and compare its origin,Medium,Requires HTML inspection and possibly URL reso...
12,SubmitInfoToEmail,Webpage forms,Inspect form actions for email-submission beha...,Medium,Requires HTML form inspection
13,NumSensitiveWords,URL / webpage text,Count sensitive terms in the exact text field ...,Medium,Must verify whether the source definition uses...
14,UrlLength,URL string,Measure URL string length,High,Can be computed directly from the URL string
15,IframeOrFrame,Webpage content,Inspect HTML for iframe or frame elements,Medium,Requires access to webpage HTML
16,HostnameLength,URL / domain,Parse URL and measure hostname length,High,Can be computed from the hostname
17,NumUnderscore,URL string,Count underscores in the URL,High,Can be computed directly from the URL string
18,PathLength,URL structure,Parse URL and measure path length,High,Can be computed from the URL string
19,QueryLength,URL structure,Parse query component and measure its length,High,Can be computed from the URL string
20,RelativeFormAction,Webpage forms,Inspect form action attributes and determine w...,Medium,Requires HTML form analysis
21,NumDashInHostname,URL / domain,Parse hostname and count hyphens,High,Can be computed from the hostname
22,ExtMetaScriptLinkRT,Webpage resources,"Inspect metadata, scripts and links for extern...",Medium,Requires HTML parsing and the original feature...
23,NumQueryComponents,URL structure,Parse query string and count components,High,Can be computed from the URL string
24,RandomString,URL / webpage text,Apply the dataset's original random-string det...,Medium,Requires the exact source definition and detec...

Saved: feature_practicality_48_reduced.csv

### 7.2. Reduced 111-feature dataset — Top 50 SHAP features

In [19]:

import pandas as pd

features_111 = [
    {"Feature": "qty_slash_url", "Category": "URL string", "Extraction_Method": "Count slashes in URL", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "time_domain_activation", "Category": "Domain registration", "Extraction_Method": "Retrieve domain creation date and calculate age", "Practicality": "Medium-Low", "Reason": "Registration data may be unavailable"},
    {"Feature": "directory_length", "Category": "URL structure", "Extraction_Method": "Parse URL path and calculate directory length", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "length_url", "Category": "URL string", "Extraction_Method": "Measure URL length", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_dot_domain", "Category": "Domain", "Extraction_Method": "Count dots in domain", "Practicality": "High", "Reason": "Parse hostname"},
    {"Feature": "ttl_hostname", "Category": "DNS", "Extraction_Method": "Retrieve DNS TTL", "Practicality": "Medium", "Reason": "Requires DNS lookup; result can vary"},
    {"Feature": "asn_ip", "Category": "IP / network", "Extraction_Method": "Resolve IP and retrieve autonomous system number", "Practicality": "Medium", "Reason": "Requires DNS and IP/ASN data"},
    {"Feature": "qty_slash_directory", "Category": "URL structure", "Extraction_Method": "Count slashes in directory path", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "time_response", "Category": "Network", "Extraction_Method": "Measure response time using a network request", "Practicality": "Medium", "Reason": "Network latency varies"},
    {"Feature": "time_domain_expiration", "Category": "Domain registration", "Extraction_Method": "Retrieve domain expiration date", "Practicality": "Medium-Low", "Reason": "Registration data may be unavailable"},
    {"Feature": "qty_redirects", "Category": "Network", "Extraction_Method": "Follow a controlled request and count redirects", "Practicality": "Medium", "Reason": "Network-dependent and potentially unsafe"},
    {"Feature": "qty_mx_servers", "Category": "DNS", "Extraction_Method": "Query DNS MX records and count servers", "Practicality": "Medium", "Reason": "Requires DNS lookup"},
    {"Feature": "domain_length", "Category": "Domain", "Extraction_Method": "Measure domain string length", "Practicality": "High", "Reason": "Direct hostname parsing"},
    {"Feature": "file_length", "Category": "URL structure", "Extraction_Method": "Parse URL path and measure filename length", "Practicality": "High", "Reason": "Usually derivable from URL path"},
    {"Feature": "domain_spf", "Category": "DNS / email security", "Extraction_Method": "Check domain SPF records using DNS", "Practicality": "Medium", "Reason": "Requires DNS lookup and exact source definition"},
    {"Feature": "qty_hyphen_directory", "Category": "URL structure", "Extraction_Method": "Count hyphens in directory path", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_nameservers", "Category": "DNS", "Extraction_Method": "Query DNS and count nameservers", "Practicality": "Medium", "Reason": "Requires DNS lookup"},
    {"Feature": "qty_vowels_domain", "Category": "Domain", "Extraction_Method": "Count vowels in domain string", "Practicality": "High", "Reason": "Direct string processing"},
    {"Feature": "tls_ssl_certificate", "Category": "TLS / certificate", "Extraction_Method": "Connect securely and inspect certificate properties", "Practicality": "Medium", "Reason": "Requires network connection; unavailable for some hosts"},
    {"Feature": "qty_dot_url", "Category": "URL string", "Extraction_Method": "Count dots in URL", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_ip_resolved", "Category": "DNS / IP", "Extraction_Method": "Resolve hostname and count returned IP addresses", "Practicality": "Medium", "Reason": "Requires DNS lookup"},
    {"Feature": "qty_dot_params", "Category": "URL structure", "Extraction_Method": "Parse query parameters and count dots in their representation", "Practicality": "High", "Reason": "Direct URL parsing; confirm source convention"},
    {"Feature": "qty_tld_url", "Category": "URL / domain", "Extraction_Method": "Count TLD-related occurrences according to source definition", "Practicality": "High", "Reason": "Requires exact source definition"},
    {"Feature": "qty_at_url", "Category": "URL string", "Extraction_Method": "Count @ characters in URL", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_hyphen_domain", "Category": "Domain", "Extraction_Method": "Count hyphens in domain", "Practicality": "High", "Reason": "Direct hostname parsing"},
    {"Feature": "qty_hyphen_url", "Category": "URL string", "Extraction_Method": "Count hyphens in URL", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "params_length", "Category": "URL structure", "Extraction_Method": "Measure query-parameter string length", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_params", "Category": "URL structure", "Extraction_Method": "Count query parameters", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "url_shortened", "Category": "URL / external lookup", "Extraction_Method": "Check URL against known shortening services or expand it safely", "Practicality": "Medium", "Reason": "Needs maintained service rules or controlled lookup"},
    {"Feature": "qty_dot_directory", "Category": "URL structure", "Extraction_Method": "Count dots in directory path", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_hyphen_file", "Category": "URL structure", "Extraction_Method": "Count hyphens in filename component", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_dot_file", "Category": "URL structure", "Extraction_Method": "Count dots in filename component", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_equal_directory", "Category": "URL structure", "Extraction_Method": "Count equals signs in directory component", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_underline_directory", "Category": "URL structure", "Extraction_Method": "Count underscores in directory component", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_underline_url", "Category": "URL string", "Extraction_Method": "Count underscores in URL", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_percent_url", "Category": "URL string", "Extraction_Method": "Count percent signs in URL", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_underline_file", "Category": "URL structure", "Extraction_Method": "Count underscores in filename component", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_percent_file", "Category": "URL structure", "Extraction_Method": "Count percent signs in filename component", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_equal_url", "Category": "URL string", "Extraction_Method": "Count equals signs in URL", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "domain_in_ip", "Category": "URL / domain", "Extraction_Method": "Check whether hostname is an IP address rather than a domain name", "Practicality": "High", "Reason": "Direct hostname parsing"},
    {"Feature": "qty_percent_directory", "Category": "URL structure", "Extraction_Method": "Count percent signs in directory component", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_equal_params", "Category": "URL structure", "Extraction_Method": "Count equals signs in query parameters", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_plus_url", "Category": "URL string", "Extraction_Method": "Count plus signs in URL", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_exclamation_directory", "Category": "URL structure", "Extraction_Method": "Count exclamation marks in directory component", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_slash_params", "Category": "URL structure", "Extraction_Method": "Count slashes in query parameter representation", "Practicality": "High", "Reason": "Direct URL parsing; confirm source convention"},
    {"Feature": "qty_percent_params", "Category": "URL structure", "Extraction_Method": "Count percent signs in query parameters", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_underline_params", "Category": "URL structure", "Extraction_Method": "Count underscores in query parameters", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "qty_comma_file", "Category": "URL structure", "Extraction_Method": "Count commas in filename component", "Practicality": "High", "Reason": "Direct URL parsing"},
    {"Feature": "tld_present_params", "Category": "URL structure", "Extraction_Method": "Check for TLD-related strings in parameters using source rule", "Practicality": "High", "Reason": "Direct parsing; exact rule must be reproduced"},
    {"Feature": "qty_tilde_directory", "Category": "URL structure", "Extraction_Method": "Count tildes in directory component", "Practicality": "High", "Reason": "Direct URL parsing"}
]

df_111_practicality = pd.DataFrame(features_111)

display(df_111_practicality)

df_111_practicality.to_csv(
    "feature_practicality_111_reduced.csv",
    index=False
)

print("Saved: feature_practicality_111_reduced.csv")

,Feature,Category,Extraction_Method,Practicality,Reason
0,qty_slash_url,URL string,Count slashes in URL,High,Direct URL parsing
1,time_domain_activation,Domain registration,Retrieve domain creation date and calculate age,Medium-Low,Registration data may be unavailable
2,directory_length,URL structure,Parse URL path and calculate directory length,High,Direct URL parsing
3,length_url,URL string,Measure URL length,High,Direct URL parsing
4,qty_dot_domain,Domain,Count dots in domain,High,Parse hostname
5,ttl_hostname,DNS,Retrieve DNS TTL,Medium,Requires DNS lookup; result can vary
6,asn_ip,IP / network,Resolve IP and retrieve autonomous system number,Medium,Requires DNS and IP/ASN data
7,qty_slash_directory,URL structure,Count slashes in directory path,High,Direct URL parsing
8,time_response,Network,Measure response time using a network request,Medium,Network latency varies
9,time_domain_expiration,Domain registration,Retrieve domain expiration date,Medium-Low,Registration data may be unavailable
10,qty_redirects,Network,Follow a controlled request and count redirects,Medium,Network-dependent and potentially unsafe
11,qty_mx_servers,DNS,Query DNS MX records and count servers,Medium,Requires DNS lookup
12,domain_length,Domain,Measure domain string length,High,Direct hostname parsing
13,file_length,URL structure,Parse URL path and measure filename length,High,Usually derivable from URL path
14,domain_spf,DNS / email security,Check domain SPF records using DNS,Medium,Requires DNS lookup and exact source definition
15,qty_hyphen_directory,URL structure,Count hyphens in directory path,High,Direct URL parsing
16,qty_nameservers,DNS,Query DNS and count nameservers,Medium,Requires DNS lookup
17,qty_vowels_domain,Domain,Count vowels in domain string,High,Direct string processing
18,tls_ssl_certificate,TLS / certificate,Connect securely and inspect certificate prope...,Medium,Requires network connection; unavailable for s...
19,qty_dot_url,URL string,Count dots in URL,High,Direct URL parsing
20,qty_ip_resolved,DNS / IP,Resolve hostname and count returned IP addresses,Medium,Requires DNS lookup
21,qty_dot_params,URL structure,Parse query parameters and count dots in their...,High,Direct URL parsing; confirm source convention
22,qty_tld_url,URL / domain,Count TLD-related occurrences according to sou...,High,Requires exact source definition
23,qty_at_url,URL string,Count @ characters in URL,High,Direct URL parsing
24,qty_hyphen_domain,Domain,Count hyphens in domain,High,Direct hostname parsing
25,qty_hyphen_url,URL string,Count hyphens in URL,High,Direct URL parsing
26,params_length,URL structure,Measure query-parameter string length,High,Direct URL parsing
27,qty_params,URL structure,Count query parameters,High,Direct URL parsing
28,url_shortened,URL / external lookup,Check URL against known shortening services or...,Medium,Needs maintained service rules or controlled l...
29,qty_dot_directory,URL structure,Count dots in directory path,High,Direct URL parsing
30,qty_hyphen_file,URL structure,Count hyphens in filename component,High,Direct URL parsing
31,qty_dot_file,URL structure,Count dots in filename component,High,Direct URL parsing
32,qty_equal_directory,URL structure,Count equals signs in directory component,High,Direct URL parsing
33,qty_underline_directory,URL structure,Count underscores in directory component,High,Direct URL parsing
34,qty_underline_url,URL string,Count underscores in URL,High,Direct URL parsing
35,qty_percent_url,URL string,Count percent signs in URL,High,Direct URL parsing
36,qty_underline_file,URL structure,Count underscores in filename component,High,Direct URL parsing
37,qty_percent_file,URL structure,Count percent signs in filename component,High,Direct URL parsing
38,qty_equal_url,URL string,Count equals signs in URL,High,Direct URL parsing
39,domain_in_ip,URL / domain,Check whether hostname is an IP address rather...,High,Direct hostname parsing
40,qty_percent_directory,URL structure,Count percent signs in directory component,High,Direct URL parsing
41,qty_equal_params,URL structure,Count equals signs in query parameters,High,Direct URL parsing
42,qty_plus_url,URL string,Count plus signs in URL,High,Direct URL parsing
43,qty_exclamation_directory,URL structure,Count exclamation marks in directory component,High,Direct URL parsing
44,qty_slash_params,URL structure,Count slashes in query parameter representation,High,Direct URL parsing; confirm source convention
45,qty_percent_params,URL structure,Count percent signs in query parameters,High,Direct URL parsing
46,qty_underline_params,URL structure,Count underscores in query parameters,High,Direct URL parsing
47,qty_comma_file,URL structure,Count commas in filename component,High,Direct URL parsing
48,tld_present_params,URL structure,Check for TLD-related strings in parameters us...,High,Direct parsing; exact rule must be reproduced
49,qty_tilde_directory,URL structure,Count tildes in directory component,High,Direct URL parsing

Saved: feature_practicality_111_reduced.csv

### Feature Practicality Analysis — Conclusion

The feature-practicality analysis evaluated the feasibility of extracting the SHAP-selected features from both reduced datasets for use in the PhishGuard website. The 48-feature dataset was reduced to 25 features, while the 111-feature dataset was reduced to 50 features.

The reduced 48-feature dataset contains both URL-based features, such as URL length, hostname length and the number of special characters, and webpage-dependent features, such as external hyperlinks, form properties and iframe usage. Extracting the latter requires access to webpage HTML and may involve browser automation.

The reduced 111-feature dataset primarily contains URL-structure features that can be calculated directly from a submitted URL. However, features related to domain registration, DNS records, IP addresses, TLS certificates and response time require external lookups or network requests. Their availability and extraction time may vary.

Overall, the 111-feature dataset's reduced feature set appears more straightforward for URL-based analysis, whereas the 48-feature dataset includes several features that may provide useful webpage-level information but require more extensive extraction. The final implementation must reproduce the original feature definitions and preprocessing used during model training to ensure reliable predictions.

These findings will be considered alongside predictive performance and computational cost when selecting the final model for PhishGuard.

## Step 8 - Computational Cost Analysis

In [21]:

# Find existing dataset and model variables in the notebook

keywords = [
    "X_train", "X_test", "y_train", "y_test",
    "X_train_reduced", "X_test_reduced",
    "top_25", "top_50", "model", "clf"
]

for name, value in sorted(globals().items()):
    if any(keyword.lower() in name.lower() for keyword in keywords):
        if not name.startswith("_"):
            try:
                shape = value.shape
                print(f"{name}: shape={shape}")
            except AttributeError:
                if hasattr(value, "predict") or isinstance(value, dict):
                    print(f"{name}: type={type(value).__name__}")

X_test: shape=(26160, 111)
X_test_25: shape=(3000, 25)
X_test_48: shape=(3000, 48)
X_test_50: shape=(26160, 50)
X_train: shape=(61037, 111)
X_train_25: shape=(7000, 25)
X_train_48: shape=(7000, 48)
X_train_50: shape=(61037, 50)
model: type=XGBClassifier
models: type=dict
models_25: type=dict
models_50: type=dict
y_test: shape=(26160,)
y_test_48: shape=(3000,)
y_train: shape=(61037,)
y_train_48: shape=(7000,)

We'll compare:

1. Training time — time required to train the model.
2. Prediction time — time to classify the test set.
3. Single-URL latency — time taken to predict one sample.
4. Model size — storage required for the trained model.
5. Predictive performance — accuracy and F1-score, to ensure efficiency doesn't come at the cost of detection quality.

In [23]:

import os
import time
import tempfile
import statistics
import joblib
import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
from xgboost import XGBClassifier

# 1. Existing train/test splits
datasets = {
    "48 Original": (X_train_48, X_test_48, y_train_48, y_test_48),
    "48 Reduced (25)": (X_train_25, X_test_25, y_train_48, y_test_48),
    "111 Original": (X_train, X_test, y_train, y_test),
    "111 Reduced (50)": (X_train_50, X_test_50, y_train, y_test),
}

# 2. Consistent benchmark model configurations
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(
        n_estimators=100, random_state=42, n_jobs=-1
    ),
    "XGBoost": XGBClassifier(
        random_state=42, eval_metric="logloss", n_jobs=-1
    ),
}

results = []

for dataset_name, (Xtr, Xte, ytr, yte) in datasets.items():
    ytr = np.asarray(ytr).ravel()
    yte = np.asarray(yte).ravel()

    for model_name, template in models.items():
        print(f"Running: {dataset_name} | {model_name}")

        # Training time: median of 3 independent fits
        train_times = []
        fitted = None

        for _ in range(3):
            clf = clone(template)
            start = time.perf_counter()
            clf.fit(Xtr, ytr)
            train_times.append(time.perf_counter() - start)
            fitted = clf

        train_time = statistics.median(train_times)

        # Warm-up before prediction timing
        first_row = Xte.iloc[[0]] if hasattr(Xte, "iloc") else Xte[:1]
        fitted.predict(first_row)

        # Full test-set prediction time: median of 5 runs
        batch_times = []
        for _ in range(5):
            start = time.perf_counter()
            predictions = fitted.predict(Xte)
            batch_times.append(time.perf_counter() - start)

        batch_time = statistics.median(batch_times)

        # Single-row prediction latency: median over up to 100 rows
        single_times = []
        n = min(100, len(Xte))

        for i in range(n):
            row = Xte.iloc[[i]] if hasattr(Xte, "iloc") else Xte[i:i+1]
            start = time.perf_counter()
            fitted.predict(row)
            single_times.append((time.perf_counter() - start) * 1000)

        single_latency_ms = statistics.median(single_times)

        # Serialized model size
        with tempfile.TemporaryDirectory() as temp_dir:
            path = os.path.join(temp_dir, "model.joblib")
            joblib.dump(fitted, path)
            model_size_mb = os.path.getsize(path) / (1024 ** 2)

        results.append({
            "Dataset": dataset_name,
            "Model": model_name,
            "Feature_Count": Xtr.shape[1],
            "Training_Time_s": train_time,
            "Full_Test_Prediction_s": batch_time,
            "Single_Row_Latency_ms": single_latency_ms,
            "Model_Size_MB": model_size_mb,
            "Accuracy_pct": accuracy_score(yte, predictions) * 100,
            "F1_pct": f1_score(yte, predictions, zero_division=0) * 100,
        })

benchmark_df = pd.DataFrame(results)

display(
    benchmark_df.sort_values(["Dataset", "Model"]).round(4)
)

benchmark_df.to_csv("phishguard_step8_benchmark.csv", index=False)
print("Saved results to phishguard_step8_benchmark.csv")

Running: 48 Original | Logistic Regression

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Running: 48 Original | Decision Tree
Running: 48 Original | Random Forest
Running: 48 Original | XGBoost
Running: 48 Reduced (25) | Logistic Regression

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Running: 48 Reduced (25) | Decision Tree
Running: 48 Reduced (25) | Random Forest
Running: 48 Reduced (25) | XGBoost
Running: 111 Original | Logistic Regression

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Running: 111 Original | Decision Tree
Running: 111 Original | Random Forest
Running: 111 Original | XGBoost
Running: 111 Reduced (50) | Logistic Regression

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Running: 111 Reduced (50) | Decision Tree
Running: 111 Reduced (50) | Random Forest
Running: 111 Reduced (50) | XGBoost

,Dataset,Model,Feature_Count,Training_Time_s,Full_Test_Prediction_s,Single_Row_Latency_ms,Model_Size_MB,Accuracy_pct,F1_pct
9,111 Original,Decision Tree,111,1.2647,0.0258,1.6383,0.3538,95.2179,93.1448
8,111 Original,Logistic Regression,111,41.3490,0.0190,1.6172,0.0039,91.8884,88.7855
10,111 Original,Random Forest,111,9.7716,0.3929,36.5373,49.1350,96.9878,95.6992
11,111 Original,XGBoost,111,2.2287,0.0832,18.5637,0.3028,96.9343,95.6113
13,111 Reduced (50),Decision Tree,50,1.0378,0.0101,1.2221,0.3532,95.3976,93.4107
12,111 Reduced (50),Logistic Regression,50,26.9562,0.0073,1.7612,0.0023,91.5520,88.0152
14,111 Reduced (50),Random Forest,50,10.2118,0.6475,36.0943,41.8558,97.0260,95.7523
15,111 Reduced (50),XGBoost,50,1.2451,0.0672,8.8089,0.3083,97.0298,95.7460
1,48 Original,Decision Tree,48,0.0880,0.0042,2.0089,0.0362,96.7333,96.7463
0,48 Original,Logistic Regression,48,1.3253,0.0032,1.6088,0.0022,95.1333,95.1592
2,48 Original,Random Forest,48,0.7869,0.0579,29.0313,5.5112,98.5667,98.5662
3,48 Original,XGBoost,48,0.2464,0.0144,8.3667,0.2068,98.7667,98.7695
5,48 Reduced (25),Decision Tree,25,0.0696,0.0019,1.4118,0.0385,96.4333,96.4558
4,48 Reduced (25),Logistic Regression,25,1.0708,0.0019,1.5092,0.0017,94.3333,94.3820
6,48 Reduced (25),Random Forest,25,0.8396,0.0486,27.5920,4.3815,98.2667,98.2678
7,48 Reduced (25),XGBoost,25,0.2946,0.0111,5.2933,0.2140,98.6000,98.6037

Saved results to phishguard_step8_benchmark.csv

What do these results tell us?
- 48-feature dataset: XGBoost with 25 features retains strong performance. Accuracy drops only from 98.77% to 98.60%, while training time increases slightly in this run.
- 111-feature dataset: XGBoost with 50 features achieves 97.03% accuracy, marginally higher than the original 96.93%. Its measured training time falls from 2.229 seconds to 1.245 seconds.
- Random Forest: It performs well, but its model files are substantially larger and its single-row prediction latency is higher than XGBoost's in these measurements.
- Decision Tree: It is fast and lightweight, but its accuracy is lower than the ensemble models.
- Logistic Regression: Its training times are unusually high on the 111-feature dataset, and the convergence warnings mean those timings and metrics should be treated cautiously.

One important distinction: these timings depend on the Colab runtime, its load, and the model settings. They are useful for comparing these configurations in this run, not universal performance guarantees.

## Step 9 — Final Model Selection

We'll use the 111-feature dataset reduced to the top 50 SHAP-ranked features, with XGBoost as our selected model.




| Parameter | Final Configuration |
|---|---|
| Dataset | 111-feature phishing dataset |
| Original number of features | 111 |
| Reduced number of features | 50 |
| Feature selection method | SHAP-based feature ranking |
| Feature reduction | 55% |
| Selected model | XGBoost Classifier |
| Accuracy | 97.03% |
| F1-score | 95.75% |
| Training time | 1.245 seconds |
| Model size | 0.31 MB |
| Final decision | Use the 50-feature reduced dataset for website implementation |


**Justification:** The 111-feature dataset was reduced to 50 features, achieving approximately 55% feature reduction while maintaining strong predictive performance. The reduced XGBoost model achieved 97.03% accuracy and a 95.75% F1-score, with lower measured training time than the original 111-feature XGBoost model. Therefore, the reduced configuration was selected for further implementation, subject to successful extraction of all required features from submitted URLs.

In [24]:

import pandas as pd
import numpy as np
from google.colab import files

# Preserve the 50 selected feature columns and their existing order
train_df = pd.DataFrame(X_train_50).copy()
test_df = pd.DataFrame(X_test_50).copy()

# Attach labels
train_df["phishing"] = np.asarray(y_train).reshape(-1)
test_df["phishing"] = np.asarray(y_test).reshape(-1)

# Preserve the original split for reproducibility
train_df["_split"] = "train"
test_df["_split"] = "test"

# Combine both sets
final_dataset = pd.concat(
    [train_df, test_df],
    ignore_index=True
)

# Put the target and split metadata last
feature_columns = list(X_train_50.columns)
final_dataset = final_dataset[
    feature_columns + ["phishing", "_split"]
]

# Save and download
filename = "phishguard_111_reduced_50_features.csv"
final_dataset.to_csv(filename, index=False)

print("Dataset shape:", final_dataset.shape)
print("Number of selected features:", len(feature_columns))
print("Class distribution:\n", final_dataset["phishing"].value_counts())
print("Train/test split:\n", final_dataset["_split"].value_counts())

files.download(filename)

Dataset shape: (87197, 52)
Number of selected features: 50
Class distribution:
 phishing
0    56706
1    30491
Name: count, dtype: int64
Train/test split:
 _split
train    61037
test     26160
Name: count, dtype: int64